import type { Content } from "./model";
export const seed: Content = {
  business: {
    name: "Signature Calendar",
    tagline: "A little everyday. A lasting impression.",
    logo: "",
    phone: "+91 9145057351",
    whatsapp: "+91 9145057351",
    email: "",
    address: "",
    hours: "",
    instagram: "",
    linkedin: "",
    other: "",
    footer: "Thoughtfully designed. Personally yours.",
  },
  home: {
    eyebrow: "THOUGHTFULLY DESIGNED. PERSONALLY YOURS.",
    title: "Personalized calendars.\nMade for your brand.",
    description:
      "Premium calendars, personalized for your brand. Beautifully considered designs that keep your business part of the everyday.",
    heroImage: "/art/botanical.svg",
    primaryLabel: "Browse Calendar Designs",
    secondaryLabel: "Contact Us",
    primaryHref: "/designs",
    secondaryHref: "/contact",
    note: "Your logo. Your story. All year long.",
    productsText:
      "Two perspectives. The same attention to detail. Find the right canvas for your brand.",
    pricingTitle: "A considered gift. A lasting connection.",
    pricingText:
      "Explore quantity-based pricing for your team, clients and community.",
    step1Title: "Choose your design",
    step1Text: "Find the artwork and format that speaks to your brand.",
    step2Title: "Make it yours",
    step2Text: "Share your logo, business details and ideas with us.",
    step3Title: "Approve the details",
    step3Text: "Review your personalized proof before production.",
    step4Title: "Welcome a new year",
    step4Text: "We confirm production and delivery with your order.",
    collectionsTitle: "Choose your calendar design.",
    collectionsText:
      "From quiet botanicals to bold perspectives, discover a design that feels like you. Then make it your own.",
    productsTitle: "Made for every kind of desk.",
    processTitle: "Your brand, beautifully in the picture.",
    qualityTitle: "It’s all in the details.",
    qualityText:
      "Considered layouts. Space for your identity. Artwork with room to breathe. We bring the details together to create a calendar that belongs on the desk.",
    contactTitle: "Let’s make your next year memorable.",
    showCollections: true,
    showProducts: true,
    showProcess: true,
    showQuality: true,
    showPricing: true,
  },
  about: {
    title: "Good design makes every day a little better.",
    body: "Signature Calendar creates personalized calendars for companies, CA firms, professionals and individuals. We believe something you see every day deserves thoughtful design.",
    approach:
      "Our approach pairs expressive artwork with clear, useful calendar layouts. Your logo and business details become a considered part of the design.",
    services:
      "Calendar design and personalization\nCorporate and professional calendars\nCustom branding and artwork\nPackaging options on request",
  },
  categories: ["Corporate", "Personalized", "Creative"],
  collections: ["Botanical studies", "Architectural notes", "Quiet landscapes"],
  designs: [
    {
      id: "botanical-studies",
      name: "Botanical studies",
      code: "SC-001",
      description:
        "A fresh perspective on the everyday. Soft greens, expressive leaves and a beautifully quiet layout.",
      format: "Horizontal",
      dimensions: "Dimensions confirmed with your quote",
      category: "Corporate",
      collection: "Botanical studies",
      cover: "/art/botanical.svg",
      gallery: [
        {
          id: "botanical-cover",
          url: "/art/botanical.svg",
          alt: "Illustrated green botanical calendar artwork",
          label: "Cover concept",
          kind: "Artwork",
          publicId: "",
        },
        {
          id: "botanical-month",
          url: "/art/month.svg",
          alt: "January 2027 calendar with botanical illustration",
          label: "January artwork",
          kind: "Artwork",
          publicId: "",
        },
      ],
      pdf: "",
      published: true,
      featured: true,
      order: 1,
      productId: "horizontal",
    },
    {
      id: "architectural-notes",
      name: "Architectural notes",
      code: "SC-002",
      description:
        "Sculptural forms and earthy hues for a desk with a different point of view.",
      format: "Vertical",
      dimensions: "Dimensions confirmed with your quote",
      category: "Creative",
      collection: "Architectural notes",
      cover: "/art/architecture.svg",
      gallery: [],
      pdf: "",
      published: true,
      featured: true,
      order: 2,
      productId: "vertical",
    },
    {
      id: "quiet-landscapes",
      name: "Quiet landscapes",
      code: "SC-003",
      description:
        "Open skies, rolling hills and a small moment of calm for every day.",
      format: "Horizontal",
      dimensions: "Dimensions confirmed with your quote",
      category: "Personalized",
      collection: "Quiet landscapes",
      cover: "/art/landscape.svg",
      gallery: [],
      pdf: "",
      published: true,
      featured: true,
      order: 3,
      productId: "horizontal",
    },
  ],
  products: [
    {
      id: "horizontal",
      name: "The horizontal calendar",
      format: "Horizontal",
      dimensions: "Confirm with your quote",
      paper: "GSM and finish available on request",
      pages: "Cover and monthly artwork, as agreed",
      binding: "Binding options available on request",
      stand: "Desk stand specification confirmed with proof",
      branding: "Company logo, contact details and brand colours",
      packaging: "Custom packaging available at an additional cost",
      moq: 100,
      description:
        "A generous canvas for beautiful artwork and your brand. A natural fit for workspaces, reception desks and everyday inspiration.",
    },
    {
      id: "vertical",
      name: "The vertical calendar",
      format: "Vertical",
      dimensions: "Confirm with your quote",
      paper: "GSM and finish available on request",
      pages: "Configuration confirmed with your quote",
      binding: "Binding options available on request",
      stand: "Desk stand specification confirmed with proof",
      branding: "Company logo, contact details and brand colours",
      packaging: "Custom packaging available at an additional cost",
      moq: 0,
      description:
        "A compact footprint with a confident presence. Thoughtfully composed for smaller spaces and distinctive designs.",
    },
  ],
  pricing: [
    {
      id: "bulk",
      name: "Horizontal desk calendars",
      productIds: ["horizontal"],
      tiers: [
        { min: 100, price: 239 },
        { min: 200, price: 229 },
        { min: 300, price: 219 },
        { min: 400, price: 209 },
        { min: 500, price: 199 },
        { min: 600, price: 189 },
      ],
      packaging: "Customized packaging is available at an additional cost.",
      tax: "Taxes: awaiting confirmation in your final quote.",
      shipping: "Delivery: awaiting confirmation in your final quote.",
    },
  ],
  faqs: [
    {
      id: "customization",
      question: "Can I add my company branding?",
      answer:
        "Yes. Choose a design and share your logo, contact details and branding requirements so we can discuss your personalized calendar.",
      published: true,
    },
    {
      id: "packaging",
      question: "Is customized packaging available?",
      answer:
        "Customized packaging is available at an additional cost. Include your requirements when requesting a quote.",
      published: true,
    },
    {
      id: "quote",
      question: "How do I get a final price?",
      answer:
        "Share your selected design, quantity and customization requirements. The final quote will confirm applicable taxes, delivery and optional extras.",
      published: true,
    },
  ],
  media: [],
  seo: [
    "home",
    "designs",
    "products",
    "pricing",
    "about",
    "contact",
    "faq",
  ].map((page) => ({
    page,
    title: `${page === "home" ? "Personalized calendars" : page[0].toUpperCase() + page.slice(1)} | Signature Calendar`,
    description:
      "Explore premium personalized desk calendars and thoughtful corporate calendar designs. Choose your artwork and make it your own.",
  })),
};
